stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Construyendo proyecto Springboot..."
    - mvn clean package


test:
  stage: test
  script:
    - echo "Testeando proyecto Springboot..."
    - mvn verify