image: maven:3.8-jdk-11

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Construyendo proyecto Springboot..."
    - mvn package
  artifacts:
    paths:
      - target/*.jar


test:
  stage: test
  script:
    - echo "Testeando proyecto Springboot..."
    - mvn verify